### libreria de Nunpy 

In [7]:
import numpy as np
a = np.zeros((2,4))

In [8]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
a.shape

(2, 4)

In [11]:
a.ndim

2

In [13]:
a.size

8

In [14]:
#creaion de arreglos
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [15]:
np.full((2,3,4),8)

array([[[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]]])

In [16]:
np.empty((2,3,9))

array([[[ 1.50915869e-316,  0.00000000e+000,  6.86083817e-310,
          6.86083956e-310,  2.78430586e-165,  6.86083817e-310,
          6.86083956e-310,  9.67804094e+276,  6.86083817e-310],
        [ 6.86083817e-310,  1.43694307e+050,  6.86083817e-310,
          6.86083947e-310,  4.85175064e-204,  6.86083817e-310,
          6.86083820e-310, -3.65443512e+304,  6.86083817e-310],
        [ 6.86083817e-310, -5.82721458e+252,  6.86083819e-310,
          6.86083817e-310,  4.33728338e-236,  6.86083817e-310,
          6.86083817e-310, -2.20359710e+252,  6.86083817e-310]],

       [[ 6.86083817e-310, -6.45076458e+019,  6.86083817e-310,
          6.86083817e-310, -1.87496146e+279,  6.86083817e-310,
          6.86083817e-310,  3.52157098e-237,  6.86083817e-310],
        [ 6.86083817e-310,  4.59107692e-166,  6.86083817e-310,
          6.86083817e-310, -5.71747866e-293,  6.86083817e-310,
          6.86083817e-310,  2.28725090e-235,  6.86083817e-310],
        [ 6.86083817e-310, -2.61916491e+124,  6.

In [17]:
np.array([1,2,3])

array([1, 2, 3])

In [18]:
np.linspace(0,3,10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [19]:
np.random.rand(2,3,4)

array([[[0.07416234, 0.66461904, 0.02350921, 0.27169592],
        [0.8826391 , 0.05823254, 0.91490543, 0.1665109 ],
        [0.35169741, 0.05264712, 0.2979814 , 0.74223878]],

       [[0.69701261, 0.05206694, 0.87277093, 0.72234689],
        [0.9484078 , 0.16399111, 0.07640874, 0.22215598],
        [0.99879996, 0.72698569, 0.41621454, 0.92652762]]])

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt


In [3]:
c= np.random.rand(100000)
plt.hist(c,bins=200)
plt.show()

NameError: name 'np' is not defined